### ISSUE TITLE
add this meta tag to your head section

### ISSUE THREAD

**Issue by rimmesbe** [MattPahuta/colmar-academy#1]
Always add this meta tag into the `<head>` section when you are using media queries:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`
This will ensure they register on all devices like smartphones and tablets.
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

https://github.com/MattPahuta/colmar-academy/blob/master/index.html#L3

**Comment by MattPahuta** [comment]
Media query-required meta tag added, update pushed to repository.
